#include<stdio.h>
int main()
{
    int arr[10][10],i,j,m,n,sum=0,max=0,max1=0;
    scanf("%d%d",&n,&m);
    for(i=0;i<n;i++)
    {
        for(j=0;j<m;j++)
        {
            scanf("%d",&arr[i][j]);
        }
    }
    for(i=0;i<n;i++)
    {
        sum=0;
        for(j=0;j<m;j++)
        {
            sum=sum+arr[i][j];
        }
        if(sum>max)
        {
            max=sum;
        }
    }
    for(j=0;j<m;j++)
    {
        sum=0;
        for(i=0;i<n;i++)
        {
            sum=sum+arr[i][j];
        }
        if(sum>max1)
        {
            max1=sum;
        }
    }

    if(max1>max)
    {
        printf("%d",max1);
    }
    else
    {
        printf("%d",max);
    }
}